server:
  port: 8080
zhem-nails:
  services:
    service:
      url: http://localhost:8081
      name: service
      password: service
file:
  storage:
    path: D:\projects\java\диплом\zhem-nails\file-storage
spring:
  servlet:
    multipart:
      max-file-size: 10MB