server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN

zhem-nails:
  services:
    service:
      url: http://localhost:8081
      name: dsakdsal
      password: ksaldkas
