server:
  port: 8081
spring:
  datasource:
    url: ${db-url:jdbc:postgresql://localhost:5432/zhem-db}
    username: ${db-username:postgres}
    password: ${db-password:root}
  flyway:
    schemas:
      - public
      - zhem
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: ${security-username:service}
      password: ${security-password:$2a$12$RoiWQYm/QrFzUnCifKrC5eCHt3IHj7PRHIaNdG7OwduR.Sltgt2ay}
      roles:
        - SERVICE
  servlet:
    multipart:
      max-file-size: 10MB
file:
  storage:
    path: ${file-storage-path:D:\projects\java\диплом\zhem-nails\file-storage}
logging:
  file:
    name: logs\logs.txt