server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zhem
    username: root
    password: root
  flyway:
    schemas:
      - public
      - zhem
  jpa:
    hibernate:
      ddl-auto: validate