server:
  port: 8081
spring:
  security:
    user:
      name: dsakdsal
      password: $2a$10$/mVp9ZSLMsSpTrpX10p2VOdgC4w/OWNT5upP3Id6sxiL1wZXCVvHC
      roles:
        - SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/zhem
    username: root
    password: root
  flyway:
    schemas:
      - public
      - zhem
  jpa:
    hibernate:
      ddl-auto: validate
